# config 配置信息里
# uri 表示 git 地址：
# label 表示 分支：
# searchPaths 表示目录：
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/fayehe/springcloudConfig/
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/